require 'rake/clean'

CLEAN.include("upfile")

module Make
  def self.upper(in_file, out_file)
    open(in_file) { |ins|
      open(out_file, "w") { |outs|
        outs.write(ins.read.upcase)
      }
    }
  end
end

file "upfile" => "downfile" do
  puts "Upcasing the downfile to upfile"
  Make.upper("downfile", "upfile")
end

task :x do |t|
  t.name # name of the task
  t.prerequisites # list of the prerequisites
end

multitask :a => [:x, :y, :z]
