source 'http://rubygems.org'

gem 'rack', '1.3.3'
gem 'rails', '3.1.1'
gem 'heroku', '~> 2.12.0', :group => :development

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

platforms :jruby do
  # gem 'activerecord-jdbcsqlite3-adapter'
  gem 'jruby-openssl'
  gem 'activerecord-jdbc-adapter', :require => false
  gem 'jdbc-sqlite3', :require => false
end

platforms :ruby do
  gem 'sqlite3-ruby', :require => 'sqlite3', :group => :development
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'turn', '< 0.8.3', :require => false
  gem "cucumber-rails"
  gem "rspec-rails"
  gem 'database_cleaner'
end

group :development, :test do
  gem "awesome_print"
end