require 'rake/clean'
require 'bluecloth'

CLOBBER.include("html")

#%+ step2
DOC_FILES = FileList['docs/*.md']

directory "html"

DOC_FILES.each do |doc_file|
  html_file = doc_file.pathmap("html/%n.html")
  desc "Build the HTML file #{html_file}"
  file html_file => ["html", doc_file] do
    content = open(doc_file) { |f| f.read }
    html = BlueCloth.new(content).to_html
    open(html_file, "w") { |f| f.write(html) }
  end
end
# %-

# %+ step3
# Using DOC_FILES defined in step 2...

HTML_FILES = DOC_FILES.pathmap("html/%n.html")

desc "Default is to create the docs"
task :default => :docs

desc "Create the documents"
task :docs => HTML_FILES
# %-
